"""initial schema

Revision ID: 409ff3f2235d
Revises: 
Create Date: 2026-08-29 02:16:35.301526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '409ff3f2235d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('brand', 'blogger', name='accounttype'), nullable=False),
    sa.Column('niche', sa.String(length=255), nullable=True),
    sa.Column('persona_summary', sa.Text(), nullable=True),
    sa.Column('persona_json', sa.Text(), nullable=True),
    sa.Column('voice_id', sa.String(length=128), nullable=True),
    sa.Column('anchor_image_url', sa.String(length=512), nullable=True),
    sa.Column('custom_reference_id', sa.String(length=64), nullable=True),
    sa.Column('telegram_channel', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('drive_folder_id', sa.String(length=128), nullable=True),
    sa.Column('launch_wave', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('instagram', name='platform'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_contexts',
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('telegram_chat_id')
    )
    op.create_table('content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('drive_file_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'rejected', 'scheduled', 'published', name='contentstatus'), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('linked_script_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['linked_script_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('instagram', name='platform'), nullable=False),
    sa.Column('key_name', sa.String(length=128), nullable=False),
    sa.Column('value_encrypted', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=False),
    sa.Column('revision_notes', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'rejected', 'scheduled', 'published', name='contentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('edited_by', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', name='role'), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    op.drop_table('prompt_templates')
    op.drop_table('generation_jobs')
    op.drop_table('credentials')
    op.drop_table('content_items')
    op.drop_table('chat_contexts')
    op.drop_table('chat_bindings')
    op.drop_table('account_platforms')
    op.drop_table('accounts')
    # ### end Alembic commands ###
